model: conv1d
batch_size: [1, 2, 4, 8, 16, 32]
input_size: [1, 2, 4, 8, 16, 32, 64, 256, 512, 1024, 2048, 3072, 4096]
num_channels: [1, 3, 5]
kernel_size: [3, 5, 7, 9]
stride: [1, 2, 5]
act_fn: "relu"
dropout: null
