batch_size: [1]
img_sizes: [224, 384] # [448, 512]
sequence_lengths: [1, 2, 4, 8, 16, 32, 64] # [128, 256, 512]
iters: 20
num_threads: 1
requires_grad: False
use_jit: True
use_cuda: False
device: "cpu"
device_idx: null
