# Device Params
device: laptop
accelerator: cpu
MaxPowerUsage: 45
OS: ubuntu2104
ISA: x86
Cpu: Intel i7-8550U
CudaArchitecture: null
AcceleratorAvailable: False
CpuCores: 8
GpuCores: null
CpuClockSpeed: 1.8e9
GpuClockSpeed: 0
MemorySpeed: 2.13e9
MemoryBandwidth: 11.36e9
Ram: 16
Vram: null

num_threads: 1
requires_grad: False
use_dynamic_quant: False
use_jit: False
use_cuda: False
